### PR TITLE
add options to getPrices

### PR DESCRIPTION
**Pull request by BrandonCardoso**
Make it so the getPrices function can handle the extra options as defined on the backpack.tf/api/prices page, such as raw and compress.

### CODE REVIEW

**Comment by KenanY** [comment]
Perhaps we might as well set `raw` to `true` by default, seeing as how whitespace is useless in JSON.

**Comment by BrandonCardoso** [comment]
The `compress` option does what you described. The `raw` option adds extra information to each item instance and has multiple possible parameters (0,1,2) that each function slightly differently.

**Comment by KenanY** [comment]
Yeah my bad, edited my comment too late :)

**Comment by KenanY** [comment]
Merged as https://github.com/KenanY/backpack.tf/commit/6699971e32b0fcd669e8b80706e6db9756dbe869 with an update to the documentation. Thanks! I've added you as a collaborator so we can review and land each other's PRs from here on out (should any more be necessary). Just a couple off the top of my head would be to default to `compress=true` and remove Node.js 0.8 from the Travis CI because it fails with `nock` (or maybe try updating `nock`).

**Pull request closed without merging**
